"use client";

import { useEffect, useRef, useState, type CSSProperties, type FormEvent, type ReactNode } from "react";
import { ArrowDownLeft, ArrowUpRight, ArrowRight, ArrowLeftRight, Check, ChevronLeft, ChevronRight, CircleHelp, Download, Eye, EyeOff, Landmark, LayoutDashboard, Mail, Plus, Search, SlidersHorizontal, Target, Trash2, Wallet, X, ShoppingBag, Utensils, Car, Zap, Music, Circle, CalendarDays, Pencil, Link2, Menu } from "lucide-react";
import { accountBalance, categories, categoryColors, isFinanceData, money, monthLabel, monthTransactions, sampleData, shortMoney, totals, type Budget, type Category, type FinanceData, type Transaction } from "../lib/finance";

type View = "Overview" | "Transactions" | "Budgets" | "Accounts" | "Inbox";
const nav = [{ name: "Overview", icon: LayoutDashboard }, { name: "Transactions", icon: ArrowLeftRight }, { name: "Budgets", icon: Target }, { name: "Accounts", icon: Landmark }, { name: "Inbox", icon: Mail }] as const;
const categoryIcons = { "Food & groceries": Utensils, Shopping: ShoppingBag, Transport: Car, "Bills & subscriptions": Zap, Lifestyle: Music, Income: ArrowDownLeft, Other: Circle };
const storageKey = "folio-demo-v1";

function IconButton({ label, children, onClick, disabled = false }: { label: string; children: ReactNode; onClick: () => void; disabled?: boolean }) {
  return <button className="icon-button" title={label} aria-label={label} onClick={onClick} disabled={disabled}>{children}</button>;
}

function Dialog({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const el = ref.current; el?.showModal(); return () => el?.close(); }, []);
  return <dialog ref={ref} className="dialog" onCancel={close} onClick={e => { if (e.target === e.currentTarget) close(); }}><div className="dialog-content"><div className="section-heading"><h2>{title}</h2><IconButton label="Close dialog" onClick={close}><X /></IconButton></div>{children}</div></dialog>;
}

export default function MoneyWorkspace({ initialView = "Overview" }: { initialView?: View }) {
  const [data, setData] = useState<FinanceData>(sampleData);
  const [ready, setReady] = useState(false);
  const [view, setView] = useState<View>(initialView);
  const [month, setMonth] = useState("2026-09");
  const [account, setAccount] = useState("all");
  const [hidden, setHidden] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [query, setQuery] = useState("");
  const [type, setType] = useState("all");
  const [category, setCategory] = useState("all");
  const [reviewOnly, setReviewOnly] = useState(false);
  const [sort, setSort] = useState("newest");
  const [filters, setFilters] = useState(false);
  const [page, setPage] = useState(1);
  const [modal, setModal] = useState<"budget" | "transaction" | "help" | null>(null);
  const [editingBudget, setEditingBudget] = useState<Budget | null>(null);
  const [selected, setSelected] = useState<Transaction | null>(null);
  const [toast, setToast] = useState("");
  const [storageError, setStorageError] = useState("");
  const [activeDay, setActiveDay] = useState<number | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    try { const saved = localStorage.getItem(storageKey); if (saved) { const parsed: unknown = JSON.parse(saved); if (isFinanceData(parsed)) setData(parsed); else setStorageError("Saved demo data could not be read. Showing the original sample."); } } catch { setStorageError("Local storage is unavailable. Changes will last for this visit only."); }
    setReady(true);
  }, []);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(""), 3500); return () => clearTimeout(timer); }, [toast]);
  function update(next: FinanceData, message: string) {
    setData(next);
    try { localStorage.setItem(storageKey, JSON.stringify(next)); } catch { setStorageError("Could not save on this device. Your changes are available for this visit."); }
    setToast(message);
  }
  function go(next: View) { setView(next); setMobileNav(false); setPage(1); setError(""); }
  function openBudget(budget: Budget | null = null) { setEditingBudget(budget); setError(""); setModal("budget"); }
  function shiftMonth(delta: number) {
    const d = new Date(`${month}-02T12:00:00`); d.setMonth(d.getMonth() + delta);
    setMonth(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`); setPage(1); setActiveDay(null);
  }
  const tx = monthTransactions(data, month, account);
  const { income, spending, net } = totals(tx);
  const monthBudgets = data.budgets.filter(b => b.month === month);
  const monthAll = monthTransactions(data, month);
  const budgetLimit = monthBudgets.reduce((s, b) => s + b.limit, 0);
  const budgetSpent = monthAll.filter(t => t.type === "out" && monthBudgets.some(b => b.category === t.category)).reduce((s, t) => s + t.amount, 0);
  const totalBalance = data.accounts.filter(a => account === "all" || a.id === account).reduce((s, a) => s + accountBalance(data, a.id), 0);
  const spendingCategories = categories.filter(c => c !== "Income").map(c => ({ category: c, amount: tx.filter(t => t.type === "out" && t.category === c).reduce((s, t) => s + t.amount, 0) })).filter(c => c.amount > 0).sort((a, b) => b.amount - a.amount);
  const visible = tx.filter(t => (!query || `${t.merchant} ${t.note} ${t.category}`.toLowerCase().includes(query.toLowerCase())) && (type === "all" || t.type === type) && (category === "all" || t.category === category) && (!reviewOnly || !t.reviewed)).sort((a, b) => sort === "highest" ? b.amount - a.amount : b.date.localeCompare(a.date));
  const displayMoney = (amount: number) => hidden ? "••••••" : money(amount);
  const pageCount = Math.max(1, Math.ceil(visible.length / 8));
  const dayCount = new Date(Number(month.slice(0, 4)), Number(month.slice(5)), 0).getDate();
  const days = Array.from({ length: dayCount }, (_, i) => totals(tx.filter(t => Number(t.date.slice(-2)) === i + 1)));
  const maxDaily = Math.max(1, ...days.flatMap(d => [d.income, d.spending]));
  const needReview = data.transactions.filter(t => !t.reviewed).length;

  function saveBudget(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const values = new FormData(e.currentTarget); const cat = values.get("category") as Category; const limit = Number(values.get("limit"));
    if (!Number.isFinite(limit) || limit <= 0) { setError("Enter a budget amount greater than zero."); return; }
    if (monthBudgets.some(b => b.category === cat && b.id !== editingBudget?.id)) { setError("This category already has a budget. Edit its existing budget instead."); return; }
    const budget: Budget = { id: editingBudget?.id ?? crypto.randomUUID(), category: cat, limit, month };
    update({ ...data, budgets: [...data.budgets.filter(b => b.id !== budget.id), budget] }, editingBudget ? "Budget updated" : "Budget created"); setModal(null);
  }
  function saveTransaction(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const values = new FormData(e.currentTarget); const amount = Number(values.get("amount")); const merchant = String(values.get("merchant") ?? "").trim();
    if (!merchant || !Number.isFinite(amount) || amount <= 0) { setError("Add a name and an amount greater than zero."); return; }
    const t: Transaction = { id: crypto.randomUUID(), merchant, amount, date: String(values.get("date")), type: values.get("type") as "in" | "out", accountId: String(values.get("account")), category: values.get("category") as Category, note: String(values.get("note") ?? ""), reviewed: true, source: "Manual" };
    update({ ...data, transactions: [t, ...data.transactions] }, "Transaction added"); setMonth(t.date.slice(0, 7)); setModal(null); setPage(1);
  }
  function exportCsv() {
    const escape = (value: unknown) => `"${String(value).replace(/^[=+@-]/, "'$&").replaceAll('"', '""')}"`;
    const csv = ["Date,Merchant,Category,Type,Amount,Account", ...visible.map(t => [t.date, t.merchant, t.category, t.type, t.amount, data.accounts.find(a => a.id === t.accountId)?.name].map(escape).join(","))].join("\r\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8;" })); const a = document.createElement("a"); a.href = url; a.download = `folio-${month}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setToast("Transactions exported");
  }

  function TransactionList({ compact = false }: { compact?: boolean }) {
    const list = compact ? [...tx].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 5) : visible.slice((Math.min(page, pageCount) - 1) * 8, Math.min(page, pageCount) * 8);
    return <div className="transaction-list">{!list.length ? <div className="empty"><Search /><h3>No transactions here</h3><p>{query || category !== "all" || type !== "all" || reviewOnly ? "Try another search or clear your filters." : "Add a transaction to start this month."}</p><button className="button" onClick={() => { setQuery(""); setCategory("all"); setType("all"); setReviewOnly(false); setPage(1); }}>Clear filters</button></div> : list.map(t => { const Icon = categoryIcons[t.category]; return <button key={t.id} className="transaction-row" onClick={() => setSelected(t)}><span className="merchant-icon" style={{ "--category": categoryColors[t.category] } as CSSProperties}><Icon size={18} /></span><span className="merchant"><strong>{t.merchant}</strong><small>{t.note || t.category}</small></span><span className="transaction-category"><i style={{ background: categoryColors[t.category] }} />{t.category}</span><span className="transaction-date">{new Date(`${t.date}T12:00:00`).toLocaleDateString("en-GB", { day: "numeric", month: "short" })}</span><span className={`transaction-amount ${t.type === "in" ? "positive" : ""}`}>{hidden ? "••••••" : `${t.type === "in" ? "+" : "−"}${money(t.amount)}`}<small>{t.reviewed ? "Reviewed" : "Needs review"}</small></span><ChevronRight size={15} /></button>; })}</div>;
  }

  return <div className="workspace">
    <a className="skip-link" href="#main">Skip to content</a>
    <aside className={`sidebar ${mobileNav ? "mobile-open" : ""}`}>
      <a className="wordmark" href="/" aria-label="Folio home"><span className="brand-mark"><span /><span /><span /></span>folio<span className="brand-period">.</span></a>
      <button className="workspace-switch" onClick={() => setModal("help")}><span className="avatar">F</span><span>Personal workspace<small>Fawaz</small></span><ChevronRight size={14} /></button>
      <nav aria-label="Main navigation">{nav.map(({ name, icon: Icon }) => <button key={name} onClick={() => go(name)} className={`nav-item ${view === name ? "active" : ""}`} aria-current={view === name ? "page" : undefined}><Icon size={19} /><span>{name}</span>{name === "Inbox" && needReview > 0 && <span className="nav-count">{needReview}</span>}</button>)}</nav>
      <div className="sidebar-month"><CalendarDays size={23} /><h3>A little planning.<br />A lot more living.</h3><p>Your money, with a plan.</p><button onClick={() => { go("Budgets"); openBudget(); }}>Make room for what matters <ArrowUpRight size={17} /></button><div className="planner-art" aria-hidden="true"><span /><span /><span /><span /><span /></div></div>
      <div className="sidebar-bottom"><button onClick={() => setModal("help")}><CircleHelp size={18} /> About this workspace</button><div className="demo-state"><i /> Demo workspace <span>NGN</span></div></div>
    </aside>

    <div className="main-shell">
      <header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Toggle navigation" onClick={() => setMobileNav(!mobileNav)}><Menu /></button><span>My workspace</span><ChevronRight size={13} /><strong>{view}</strong></div><div className="topbar-actions"><span className="sample-label">Sample data</span><IconButton label={hidden ? "Show balances" : "Hide balances"} onClick={() => setHidden(!hidden)}>{hidden ? <EyeOff /> : <Eye />}</IconButton><button className="profile-avatar" title="About your workspace" onClick={() => setModal("help")}>F</button></div></header>
      <main id="main">
        {storageError && <div className="notice" role="alert">{storageError}<IconButton label="Dismiss notice" onClick={() => setStorageError("")}><X /></IconButton></div>}
        <div className="page-heading"><div><h1>{view === "Overview" ? "Your money. In perspective." : view === "Budgets" ? "Give every naira a direction." : view === "Transactions" ? "The everyday, accounted for." : view === "Accounts" ? "All your money, together." : "From inbox to insight."}</h1><p>{view === "Overview" ? "Good to see you, Fawaz. Here's where things stand." : view === "Budgets" ? "Make space for the essentials. And the things you love." : view === "Transactions" ? "A clear view of what came in and what went out." : view === "Accounts" ? "Your balances across the whole picture." : "Review the details behind your money."}</p></div><button className="button primary" onClick={() => { if (view === "Budgets") openBudget(); else { setError(""); setModal("transaction"); } }} disabled={!ready}><Plus size={17} />{view === "Budgets" ? "Create budget" : "Add transaction"}</button></div>
        {view !== "Inbox" && <div className="period-bar"><div className="period-control"><IconButton label="Previous month" onClick={() => shiftMonth(-1)}><ChevronLeft /></IconButton><span>{monthLabel(month)}</span><IconButton label="Next month" onClick={() => shiftMonth(1)}><ChevronRight /></IconButton></div>{view !== "Budgets" && <select aria-label="Filter account" value={account} onChange={e => { setAccount(e.target.value); setPage(1); }}><option value="all">All accounts</option>{data.accounts.map(a => <option value={a.id} key={a.id}>{a.name}</option>)}</select>}<span className="period-note">{view === "Budgets" ? "Monthly budgets · all accounts" : "Your monthly snapshot"}</span></div>}

        {view === "Overview" && <>
          <section className="money-overview" aria-label="Balance and cash flow">
            <div className="balance-block"><div className="metric-label"><Wallet size={17} /> Total balance <span>All time</span></div><div className="balance-number">{displayMoney(totalBalance)}</div><div className="balance-note"><span className={net >= 0 ? "positive" : "negative"}>{net >= 0 ? <ArrowUpRight size={15} /> : <ArrowDownLeft size={15} />}{displayMoney(Math.abs(net))}</span> {net >= 0 ? "net added" : "net spent"} this month</div><div className="account-chips">{data.accounts.filter(a => account === "all" || a.id === account).map(a => <button key={a.id} onClick={() => { setAccount(a.id); go("Accounts"); }}><i style={{ background: a.color }} />{a.name}<ArrowUpRight size={12} /></button>)}</div></div>
            <div className="flow-block"><div className="flow-head"><span>THIS MONTH</span><span>{income ? Math.round(net / income * 100) : 0}% {net >= 0 ? "retained" : "net deficit"}</span></div><div className="flow-row"><span className="flow-icon income"><ArrowDownLeft size={18} /></span><div><span>Money in</span><strong>{displayMoney(income)}</strong></div><div className="flow-track"><span className="in-bar" style={{ width: `${income / Math.max(income, spending, 1) * 100}%` }} /></div></div><div className="flow-row"><span className="flow-icon expense"><ArrowUpRight size={18} /></span><div><span>Money out</span><strong>{displayMoney(spending)}</strong></div><div className="flow-track"><span className="out-bar" style={{ width: `${spending / Math.max(income, spending, 1) * 100}%` }} /></div></div></div>
          </section>

          <div className="overview-grid">
            <section className="cash-section"><div className="section-heading"><h2>The ebb & flow</h2><div className="legend"><span><i className="green" /> Money in</span><span><i className="coral" /> Money out</span></div></div><div className="chart-caption"><strong>{displayMoney(activeDay ? days[activeDay - 1].income - days[activeDay - 1].spending : net)}</strong><span>{activeDay ? `${activeDay} ${monthLabel(month).split(" ")[0]} · net cash flow` : "net cash flow this month"}</span>{activeDay && <button className="text-button" onClick={() => setActiveDay(null)}>Reset</button>}</div><div className="chart"><div className="chart-axis"><span>{hidden ? "•••" : shortMoney(maxDaily)}</span><span>{hidden ? "•••" : shortMoney(maxDaily / 2)}</span><span>0</span></div><div className="daily-bars">{days.map((day, i) => <button key={i} className={`day-column ${activeDay === i + 1 ? "selected" : ""}`} aria-label={`${i + 1} ${month}: ${hidden ? "balances hidden" : `${money(day.income)} in, ${money(day.spending)} out`}`} title={hidden ? `Day ${i + 1}` : `Day ${i + 1}: ${money(day.income)} in / ${money(day.spending)} out`} onClick={() => setActiveDay(i + 1)}><span className="day-pair"><i className="day-in" style={{ height: `${day.income / maxDaily * 100}%` }} /><i className="day-out" style={{ height: `${day.spending / maxDaily * 100}%` }} /></span><span className="day-label">{[0, 4, 9, 14, 19, 24, dayCount - 1].includes(i) ? String(i + 1).padStart(2, "0") : ""}</span></button>)}</div></div><div className="chart-footer"><span>{monthLabel(month)}</span><span>Daily cash flow <ArrowRight size={13} /></span></div></section>
            <section className="spending-section"><div className="section-heading"><h2>Where it went</h2><ArrowUpRight size={18} /></div><p className="section-subtitle">A closer look at your spending</p><div className="spending-strip" role="img" aria-label="Spending proportions by category">{spendingCategories.map(c => <button key={c.category} aria-label={`View ${c.category} transactions`} style={{ flex: c.amount, background: categoryColors[c.category] }} onClick={() => { setCategory(c.category); go("Transactions"); }} />)}</div><div className="category-list">{spendingCategories.length ? spendingCategories.map(c => <button key={c.category} onClick={() => { setCategory(c.category); go("Transactions"); }}><i style={{ background: categoryColors[c.category] }} /><span>{c.category}</span><strong>{displayMoney(c.amount)}</strong><small>{Math.round(c.amount / spending * 100)}%</small></button>) : <p className="empty-small">No spending this month.</p>}</div></section>
          </div>
          <div className="lower-grid"><section className="recent-section"><div className="section-heading"><h2>Recent transactions</h2><button className="text-button" onClick={() => { setCategory("all"); go("Transactions"); }}>View all <ArrowRight size={15} /></button></div><TransactionList compact /></section><section className="budget-snapshot"><div className="section-heading"><h2>A plan you can live with.</h2><Target size={23} /></div><p>{budgetLimit ? `${Math.round(budgetSpent / budgetLimit * 100)}% of your monthly budget used` : "A fresh month. A fresh plan."}</p><div className="budget-ticks" aria-label={`${Math.round(budgetSpent / Math.max(budgetLimit, 1) * 100)} percent used`}>{Array.from({ length: 30 }, (_, i) => <i key={i} className={i / 30 < budgetSpent / Math.max(budgetLimit, 1) ? "filled" : ""} />)}</div><div className="budget-remaining"><strong>{displayMoney(Math.abs(budgetLimit - budgetSpent))}</strong><span>{budgetSpent > budgetLimit ? "over budget" : "left to spend"}</span></div><button onClick={() => go("Budgets")}>Check your budgets <ArrowUpRight size={18} /></button></section></div>
        </>}

        {view === "Transactions" && <section className="ledger"><div className="ledger-toolbar"><label className="search-field"><Search size={17} /><input aria-label="Search transactions" placeholder="Find a transaction..." value={query} onChange={e => { setQuery(e.target.value); setPage(1); }} /></label><div className="segmented">{[["all", "All"], ["in", "Money in"], ["out", "Money out"]].map(([value, label]) => <button key={value} aria-pressed={type === value} className={type === value ? "selected" : ""} onClick={() => { setType(value); setPage(1); }}>{label}</button>)}</div><IconButton label="Toggle filters" onClick={() => setFilters(!filters)}><SlidersHorizontal /></IconButton><IconButton label="Export transactions" onClick={exportCsv}><Download /></IconButton></div>{filters && <div className="filter-bar"><select aria-label="Category" value={category} onChange={e => { setCategory(e.target.value); setPage(1); }}><option value="all">All categories</option>{categories.map(c => <option key={c}>{c}</option>)}</select><select aria-label="Sort transactions" value={sort} onChange={e => setSort(e.target.value)}><option value="newest">Newest first</option><option value="highest">Highest amount</option></select><label className="check-label"><input type="checkbox" checked={reviewOnly} onChange={e => { setReviewOnly(e.target.checked); setPage(1); }} /> Needs review</label></div>}{category !== "all" && <div className="active-filter">{category}<IconButton label="Clear category filter" onClick={() => setCategory("all")}><X /></IconButton></div>}<div className="ledger-summary"><span>{visible.length} transactions</span><span>In <b>{displayMoney(totals(visible).income)}</b></span><span>Out <b>{displayMoney(totals(visible).spending)}</b></span></div><TransactionList /><div className="pagination"><span>Page {Math.min(page, pageCount)} of {pageCount}</span><IconButton label="Previous page" disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft /></IconButton><IconButton label="Next page" disabled={page >= pageCount} onClick={() => setPage(page + 1)}><ChevronRight /></IconButton></div></section>}

        {view === "Budgets" && <><section className="budget-banner"><div><span>Your monthly plan</span><strong>{displayMoney(budgetLimit)}</strong></div><div><span>Spent in budgeted categories</span><strong>{displayMoney(budgetSpent)}</strong></div><div><span>{budgetSpent > budgetLimit ? "Over budget" : "Still available"}</span><strong>{displayMoney(Math.abs(budgetLimit - budgetSpent))}</strong></div></section><div className="budget-grid">{monthBudgets.map(b => { const spent = monthAll.filter(t => t.type === "out" && t.category === b.category).reduce((s, t) => s + t.amount, 0); const percent = Math.round(spent / b.limit * 100); const Icon = categoryIcons[b.category]; return <article className="budget-card" key={b.id}><div className="section-heading"><span className="category-symbol" style={{ background: categoryColors[b.category] }}><Icon size={20} /></span><IconButton label={`Edit ${b.category} budget`} onClick={() => openBudget(b)}><Pencil /></IconButton></div><h2>{b.category}</h2><div className="budget-value"><strong>{displayMoney(spent)}</strong><span> / {displayMoney(b.limit)}</span></div><div className="progress-track" role="progressbar" aria-label={`${b.category} budget used`} aria-valuenow={Math.min(percent, 100)} aria-valuemin={0} aria-valuemax={100} aria-valuetext={`${percent}% used`}><span style={{ width: `${Math.min(percent, 100)}%`, background: percent > 100 ? "#bd4935" : categoryColors[b.category] }} /></div><div className="budget-status"><span className={percent >= 90 ? "negative" : ""}>{percent > 100 ? "Over budget" : percent >= 90 ? "Getting close" : "On track"}</span><strong>{displayMoney(Math.abs(b.limit - spent))} {spent > b.limit ? "over" : "left"}</strong></div></article>; })}<button className="new-budget" onClick={() => openBudget()}><Plus size={28} /><strong>Create a budget</strong><span>Make room for something new</span></button></div><p className="budget-footnote">Spending outside your budgets: <strong>{displayMoney(totals(monthAll).spending - budgetSpent)}</strong></p></>}

        {view === "Accounts" && <><section className="account-total"><span>Total balance · all time</span><strong>{displayMoney(totalBalance)}</strong><p>Opening balances plus all recorded money in and out.</p></section><div className="account-grid">{data.accounts.filter(a => account === "all" || a.id === account).map(a => <article className="account-card" key={a.id}><div className="section-heading"><span className="bank-mark" style={{ background: a.color }}><Landmark /></span><span className="sample-label">Sample account</span></div><h2>{a.name}</h2><p>{a.kind}</p><strong>{displayMoney(accountBalance(data, a.id))}</strong><div className="account-movement"><span>In this month<b className="positive">{displayMoney(totals(monthTransactions(data, month, a.id)).income)}</b></span><span>Out this month<b>{displayMoney(totals(monthTransactions(data, month, a.id)).spending)}</b></span></div><button className="text-button" onClick={() => { setAccount(a.id); setCategory("all"); go("Transactions"); }}>View transactions <ArrowRight size={16} /></button></article>)}</div></>}

        {view === "Inbox" && <><section className="connection-section"><div className="connection-art"><Mail size={36} /><span><Link2 size={19} /></span></div><div><h2>Your inbox, connected to the bigger picture.</h2><p>Email connection is not set up. Your workspace currently uses sample transactions.</p><span className="connection-status"><i /> Not connected</span></div></section><section className="review-section"><div className="section-heading"><h2>Needs a second look</h2><span>{needReview} to review</span></div>{data.transactions.filter(t => !t.reviewed).map(t => <button key={t.id} className="review-row" onClick={() => setSelected(t)}><Mail size={20} /><span><strong>{t.merchant}</strong><small>{t.note} · {t.source}</small></span><strong>{displayMoney(t.amount)}</strong><ArrowRight size={18} /></button>)}{!needReview && <div className="empty"><Check /><h3>All caught up.</h3><p>Every transaction has been reviewed.</p></div>}</section></>}
        <footer className="page-footer"><span>Made for your everyday.</span><span>Folio · Personal finance <span className="footer-dot">/</span> Sample workspace</span></footer>
      </main>
    </div>
    {toast && <div className="toast" role="status"><Check size={17} />{toast}</div>}

    {modal === "budget" && <Dialog title={editingBudget ? "Edit your budget" : "Make a little room."} close={() => setModal(null)}><p className="dialog-subtitle">{monthLabel(month)} · all accounts</p><form onSubmit={saveBudget}><label>Category<select name="category" defaultValue={editingBudget?.category ?? categories.filter(c => c !== "Income" && !monthBudgets.some(b => b.category === c))[0]}>{categories.filter(c => c !== "Income").map(c => <option key={c} disabled={monthBudgets.some(b => b.category === c && b.id !== editingBudget?.id)}>{c}</option>)}</select></label><label>Monthly limit (NGN)<input name="limit" type="number" min="1" max="100000000000" step="0.01" required placeholder="50,000" defaultValue={editingBudget?.limit} autoFocus /></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions">{editingBudget && <button type="button" className="button danger" onClick={() => { update({ ...data, budgets: data.budgets.filter(b => b.id !== editingBudget.id) }, "Budget deleted"); setModal(null); }}><Trash2 size={16} /> Delete</button>}<button className="button primary" type="submit">{editingBudget ? "Save budget" : "Create budget"}<ArrowRight size={16} /></button></div></form></Dialog>}
    {modal === "transaction" && <Dialog title="Add a transaction" close={() => setModal(null)}><form onSubmit={saveTransaction}><div className="form-columns"><label>Money<select name="type"><option value="out">Money out</option><option value="in">Money in</option></select></label><label>Amount (NGN)<input name="amount" type="number" min="0.01" step="0.01" max="100000000000" required placeholder="0.00" /></label></div><label>Name<input name="merchant" required maxLength={100} placeholder="Who was it to or from?" /></label><div className="form-columns"><label>Date<input name="date" type="date" required defaultValue={`${month}-06`} /></label><label>Account<select name="account" defaultValue={account === "all" ? data.accounts[0].id : account}>{data.accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><label>Category<select name="category">{categories.map(c => <option key={c}>{c}</option>)}</select></label><label>Note <span className="muted">(optional)</span><input name="note" maxLength={160} placeholder="A little context for later" /></label>{error && <p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button className="button primary" type="submit">Add transaction <Plus size={16} /></button></div></form></Dialog>}
    {selected && <Dialog title="Transaction details" close={() => setSelected(null)}><div className="detail-heading"><span className="merchant-icon" style={{ "--category": categoryColors[selected.category] } as CSSProperties}>{selected.type === "in" ? <ArrowDownLeft /> : <ArrowUpRight />}</span><h3>{selected.merchant}</h3><strong className={selected.type === "in" ? "positive" : ""}>{displayMoney(selected.amount)}</strong><p>{selected.note}</p></div><dl className="detail-list"><div><dt>Date</dt><dd>{selected.date}</dd></div><div><dt>Account</dt><dd>{data.accounts.find(a => a.id === selected.accountId)?.name}</dd></div><div><dt>Source</dt><dd>{selected.source}</dd></div><div><dt>Status</dt><dd>{selected.reviewed ? "Reviewed" : "Needs review"}</dd></div></dl><label className="detail-category">Category<select value={selected.category} onChange={e => { const changed = { ...selected, category: e.target.value as Category }; update({ ...data, transactions: data.transactions.map(t => t.id === changed.id ? changed : t) }, "Category updated"); setSelected(changed); }}>{categories.map(c => <option key={c}>{c}</option>)}</select></label><div className="form-actions"><button className="button danger" onClick={() => { update({ ...data, transactions: data.transactions.filter(t => t.id !== selected.id) }, "Transaction deleted"); setSelected(null); }}><Trash2 size={16} />Delete</button><button className="button primary" disabled={selected.reviewed} onClick={() => { const changed = { ...selected, reviewed: true }; update({ ...data, transactions: data.transactions.map(t => t.id === selected.id ? changed : t) }, "Transaction reviewed"); setSelected(changed); }}><Check size={16} />{selected.reviewed ? "Reviewed" : "Mark reviewed"}</button></div></Dialog>}
    {modal === "help" && <Dialog title="Your personal workspace" close={() => setModal(null)}><p className="help-copy">Welcome, Fawaz. This is a sample workspace. Balances and transactions are illustrative, and edits are saved only in this browser.</p><p className="help-copy">No bank or email account is connected. Folio is a working name.</p><button className="button" onClick={() => setModal(null)}>Back to my money <ArrowRight size={16} /></button></Dialog>}
  </div>;
}
